* TErm Rewriting Framework (TeRF)

TeRF is a python 2 library for describing, computing with, and learning Term Rewriting Systems (TRS).

** Term Rewriting Systems (TRSs)

TRSs are a simple formalism from theoretical computer science used to model the behavior and evolution of tree-based structures like natural langauge parse trees or abstract syntax trees.

A TRS is defined in two parts. The first is a set, /S/, of symbols. /S/ is called the signature and together with a disjoint set of variables, defines the set of all possible trees, or terms, which the system can consider. The second is a set, /R/, of rewrite rules. A rewrite rule is an equation, /s = t/, and is interpreted as follows: any term matching the pattern described by /s/ can be rewritten according to the pattern described by /t/. Together /S/ and /R/ define a TRS that describes a system of computation, which can often be considered as a sort of programming language. TeRF provides a way to describe arbitrary TRSs.

** The ~terf~ utility

~terf~ provides a processor for *.terf files with both batch and interactive modes. From the base directory, run ~./bin/terf -h~ for details.

** Further Reading

- Baader & Nipkow (1999). [[http://www.cambridge.org/us/academic/subjects/computer-science/programming-languages-and-applied-logic/term-rewriting-and-all?format=PB&isbn=9780521779203][Term rewriting and all that]]. Cambridge University Press.
- Bezem, Klop, & de Vrijer (Eds.) (2003). [[http://www.cambridge.org/us/academic/subjects/computer-science/programming-languages-and-applied-logic/term-rewriting-systems?format=HB&isbn=9780521391153][Term Rewriting Systems]]. Cambridge University Press.
- [[https://en.wikipedia.org/wiki/Rewriting][Rewriting]]. (2017). Wikipedia.
